name: Inputs Test

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: display inputs.tag
        run: echo ${{ inputs.tag }}
      - name: display github.event.inputs.tag
        run: echo ${{ github.event.inputs.tag }}
