name: No-build keyword test
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ !(github.event_name == 'push' && contains(github.event.head_commit.message, '@@__LNN_NO_BUILD__@@')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
